# Generated by Django 5.2.7 on 2025-10-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskForms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("genero", models.CharField(max_length=10)),
                ("peso", models.FloatField()),
                ("talla", models.FloatField()),
                ("Distrito", models.CharField(max_length=100)),
            ],
        ),
    ]
