# Generated by Django 5.2.7 on 2025-10-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formTasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskforms",
            old_name="Distrito",
            new_name="distrito",
        ),
        migrations.AddField(
            model_name="taskforms",
            name="cred",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskforms",
            name="suplementacion",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
